FROM certbot/certbot

CMD ["certonly", "--webroot", "-w=/var/www/help-desk", "--email", "help-desc@gmail.com", "--agree-tos", "--no-eff-email", "-d", "help-desk.ai"]
CMD ["certonly", "--webroot", "-w=/var/www/app.help-desk", "--email", "help-desc@gmail.com", "--agree-tos", "--no-eff-email", "-d", "app.help-desk.ai"]