FROM nginx:latest

# Create log files for laravel
ADD . /var/log/nginx/laravel

RUN touch /var/log/nginx/laravel/access.log
RUN touch /var/log/nginx/laravel/error.log

# Create log files for laravel
ADD . /var/log/nginx/laravel

RUN touch /var/log/nginx/laravel/access.log
RUN touch /var/log/nginx/laravel/error.log

EXPOSE 80
